### ISSUE TITLE
Add an open source license? 

### ISSUE THREAD

**Issue by jasonblais** [ssor/bom#1]
Thanks for sharing this project! We'd love to use it as part of the Mattermost open source project (https://www.mattermost.org/) in our [webapp](https://github.com/mattermost/platform).

Would you consider adding either an MIT or an Apache 2.0 license? 

To do so, in GitHub you can hit "Create new file" and name a file `LICENSE.txt`

![image](https://cloud.githubusercontent.com/assets/177788/19657017/36238482-99d7-11e6-9fd0-f507970891c7.png)

This will prompt GitHub to offer a license template: 

![image](https://cloud.githubusercontent.com/assets/177788/19657044/5a2d8b66-99d7-11e6-8164-ac7f90b10646.png)

If you use either an MIT license or an Apache 2.0 license it would make it easy to add your work to other open source projects, and we'd love to include your work in ours. 

Thanks kindly for your consideration.

**Comment by jasonblais** [comment]
Hey @ssor, 

thanks again for sharing this project! 

Wondering if you'd be open to adding either an MIT or an Apache 2.0 license? If you use either, it would make it easy to add your work to other open source projects, and we'd love to include your work in ours.

Don't hesitate to let me know if you have any questions.

**Comment by MTecknology** [comment]
I am attempting to package gitea for Debian, but this library is a dependency and it cannot be packaged without this project having a license applied. I would encourage you to adopt the MIT license for this source.

**Comment by ssor** [comment]
MIT License  added, thanks

**Comment by MTecknology** [comment]
Thanks!
